# Site settings
title: Virada Hacker
email: lampiaosec@riseup.net
description: Site do Virada Hacker!

baseurl: "/virada-hacker" # the subpath of your site, e.g. /blog/
url: "https://lampiaosec.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: lampiaosec
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/lampiaosec/virada-hacker/blob/gh-pages/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/lampiaosec/virada-hacker/new/gh-pages
#########################################
disqus: viradahacker
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
